name: one_clock
version: 2.0.1
description: "Flutter analog and digital clock plugin. This plugin can be used to draw beautiful analog as well as digital clock for your flutter application"
homepage: https://github.com/AurangzebHusain/one_clock

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
